import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

/**
 * Report Generator Utility
 * Generates PDF reports for various financial documents
 */

class ReportGenerator {
  constructor() {
    this.primaryColor = '#4F46E5'; // Indigo
    this.secondaryColor = '#6B7280'; // Gray
    this.successColor = '#10B981'; // Green
    this.dangerColor = '#EF4444'; // Red
  }

  /**
   * Create a new PDF document with standard settings
   */
  createDocument() {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50,
      bufferPages: true
    });

    return doc;
  }

  /**
   * Add header to PDF with logo and chama name
   */
  addHeader(doc, chamaName, reportTitle, reportDate) {
    doc
      .fontSize(20)
      .fillColor(this.primaryColor)
      .text('AkibaPlus', 50, 50);

    doc
      .fontSize(16)
      .fillColor('#000')
      .text(chamaName, 50, 75);

    doc
      .fontSize(12)
      .fillColor(this.secondaryColor)
      .text(reportTitle, 50, 100)
      .text(`Generated: ${reportDate}`, 50, 115);

    // Add horizontal line
    doc
      .moveTo(50, 140)
      .lineTo(545, 140)
      .stroke(this.secondaryColor);

    return doc;
  }

  /**
   * Add footer with page numbers
   */
  addFooter(doc) {
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);

      // Footer line
      doc
        .moveTo(50, 770)
        .lineTo(545, 770)
        .stroke(this.secondaryColor);

      // Page number
      doc
        .fontSize(9)
        .fillColor(this.secondaryColor)
        .text(
          `Page ${i + 1} of ${pages.count}`,
          50,
          780,
          { align: 'center', width: 495 }
        );

      // Timestamp
      doc
        .fontSize(8)
        .text(
          'Generated by AkibaPlus - Financial Management System',
          50,
          790,
          { align: 'center', width: 495 }
        );
    }
  }

  /**
   * Add table to PDF
   */
  addTable(doc, dataOrConfig, config) {
    // Backward-compatible signature support:
    // addTable(doc, config) and addTable(doc, data, config)
    const tableConfig = config || dataOrConfig;
    const { headers, rows, startY = 160, columnWidths } = tableConfig;
    let y = startY;

    // Calculate column widths if not provided
    const totalWidth = 495;
    const colCount = headers.length;
    const widths = columnWidths || Array(colCount).fill(totalWidth / colCount);

    // Draw header row
    doc.fontSize(10).fillColor('#fff');
    let x = 50;
    headers.forEach((header, i) => {
      doc.rect(x, y, widths[i], 25).fill(this.primaryColor);
      doc.text(header, x + 5, y + 7, { width: widths[i] - 10 });
      x += widths[i];
    });

    y += 25;

    // Draw data rows
    doc.fillColor('#000').fontSize(9);
    rows.forEach((row, rowIndex) => {
      // Check if we need a new page
      if (y > 720) {
        doc.addPage();
        y = 50;
      }

      x = 50;
      const bgColor = rowIndex % 2 === 0 ? '#F9FAFB' : '#FFFFFF';
      
      row.forEach((cell, i) => {
        doc.rect(x, y, widths[i], 20).fill(bgColor).stroke('#E5E7EB');
        doc.fillColor('#000').text(String(cell || '-'), x + 5, y + 5, { 
          width: widths[i] - 10,
          ellipsis: true 
        });
        x += widths[i];
      });

      y += 20;
    });

    return y + 10; // Return next Y position
  }

  /**
   * Add summary section with key-value pairs
   */
  addSummarySection(doc, title, items, startY = 160) {
    let y = startY;

    doc
      .fontSize(14)
      .fillColor(this.primaryColor)
      .text(title, 50, y);

    y += 25;

    doc.fontSize(10).fillColor('#000');
    items.forEach(({ label, value, color }) => {
      const valueColor = color || '#000';
      
      doc.text(label, 50, y);
      doc.fillColor(valueColor).text(value, 300, y, { align: 'right', width: 245 });
      doc.fillColor('#000');
      
      y += 20;
    });

    return y + 10;
  }

  /**
   * Convert currency to formatted string
   */
  formatCurrency(amount) {
    return new Intl.NumberFormat('en-KE', {
      style: 'currency',
      currency: 'KES',
      minimumFractionDigits: 2
    }).format(amount || 0);
  }

  /**
   * Format date
   */
  formatDate(date) {
    return new Date(date).toLocaleDateString('en-KE', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  }

  /**
   * Convert PDF document to buffer
   */
  async toBuffer(doc) {
    return new Promise((resolve, reject) => {
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
      doc.end();
    });
  }
}

export default new ReportGenerator();
