-- Grant necessary permissions to chama_app user
GRANT ALL ON SCHEMA public TO chama_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO chama_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO chama_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO chama_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO chama_app;
